name: Build image on Tag
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - name: Use Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # TODO: tests when ready
      
      - name: Copy to docker
        run: cp -r build/ docker/build
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: docker
          registry: docker.pkg.github.com
          repository: mpapenbr/iracelog/iracelog-web
          tag_with_ref: true
